import type { CombinedData } from "~/data/palCombinedData";

export const columnOrder: (keyof CombinedData)[] = [
    "Name",
    "ElementType1",
    "ElementType2",
    "ZukanIndex",
    "MinimumSphere",
    "SlowWalkSpeed",
    "WalkSpeed",
    "RunSpeed",
    "RideSprintSpeed",
    "SwimSpeed",
    "SwimDashSpeed",
    "Stamina",
    "WorkSuitability_EmitFlame",
    "WorkSuitability_Seeding",
    "WorkSuitability_Handcraft",
    "WorkSuitability_Deforest",
    "WorkSuitability_ProductMedicine",
    "WorkSuitability_Transport",
    "WorkSuitability_Watering",
    "WorkSuitability_GenerateElectricity",
    "WorkSuitability_Collection",
    "WorkSuitability_Mining",
    "WorkSuitability_Cool",
    "WorkSuitability_MonsterFarm",
    "Rarity",
    "Hp",
    "MeleeAttack",
    "ShotAttack",
    "Defense",
    "CraftSpeed",
];

export const defaultHiddenColumns: (keyof CombinedData)[] = [
    "Id",
    "OverrideNameTextID",
    "NamePrefixID",
    "OverridePartnerSkillTextID",
    "IsPal",
    "Tribe",
    "BPClass",
    "ZukanIndexSuffix",
    "Organization",
    "IsBoss",
    "IsTowerBoss",
    "IsRaidBoss",
    "UseBossHPGauge",
    "BattleBGM",
    "ViewingDistance",
    "ViewingAngle",
    "MeshCapsuleHalfHeight",
    "MeshCapsuleRadius",
    // @ts-expect-error -- This will be removed from the object before it's used
    "MeshRelativeLocation",
];
